version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/antham/strumt
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.27.0
      - run:
          name: Install vendors
          command: |
            export GO111MODULE=on
            go mod vendor
      - run:
          name: Run tests
          command: |
            make test-all
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)
