version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/antham/strumt
    steps:
      - checkout
      - run:
          name: Install dep and gometalinter
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get github.com/alecthomas/gometalinter
            gometalinter --install --update
      - run:
          name: Install vendors
          command: |
            dep ensure -v
      - run:
          name: Run tests
          command: |
            make test-all
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)
